# Generated by Django 3.2.18 on 2023-02-24 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='order',
            new_name='sort_order',
        ),
    ]
