# Generated by Django 4.1.7 on 2023-02-24 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("watchlist", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(name="section", unique_together={("course",)},),
    ]
