# Generated by Django 4.1.7 on 2023-02-24 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("watchlist", "0002_alter_section_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(name="section", unique_together=set(),),
        migrations.AlterField(
            model_name="course",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="url",
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name="section",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
