version: "3"
services:
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    env_file: ./.env
    volumes:
      - ../frontend:/app
    ports:
      - ${FRONTEND_PORT}:3000
    tty: true
    restart: always

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    command: "/code/startup.sh"
    working_dir: /code
    env_file: ./.env
    ports:
      - ${BACKEND_PORT}:8000
    volumes:
      - ../backend:/code
    depends_on:
      - db

  db:
    image: mysql:8.0
    env_file: ./.env
    volumes:
      - ./mysql/:/var/lib/mysql
    ports:
      - ${MYSQL_PORT}:3306
